### ISSUE TITLE
-xsl flag does not work as intended

### ISSUE THREAD

**Issue by zdefne-usgs** [Unidata/threddsIso#59]
I am trying to do this on my desktop with the -custom and -xls the flags: 
```
 java -Xms1024m -Xmx1024m -jar ncISO-2.3.5.jar -ts https://geoport.usgs.esipfed.org/thredds/sand/usgs/Projects/BBLEH/run071tRX/catalog.xml -num 1 -depth 1 -iso true -custom true -xslt UnidataDD2MI_dev.xsl
 ```

but I get this error:
```
ERROR [main] (DatasetTreeService.java:229) - _id=1
thredds.server.metadata.exception.ThreddsUtilitiesException: Configuration problem: xsl/null TransformerConfigurationException. D:\Documents\DATA_RELEASE\ISOcompare\standalone_ISO\xsl\null (The system cannot find the file specified)
        at thredds.server.metadata.util.ThreddsTranslatorUtil.doTransform(ThreddsTranslatorUtil.java:307)
        at thredds.server.metadata.util.ThreddsTranslatorUtil.transform(ThreddsTranslatorUtil.java:199)
        at gov.noaa.eds.service.DatasetTreeService.getNodes(DatasetTreeService.java:213)
...
```
ncISO is trying to locate the style sheet here:
```
D:\Documents\DATA_RELEASE\ISOcompare\standalone_ISO\xsl\null
```

I tried with placing the XSL in the same folder and with/without the folder name in the command line but no luck. 

This works without the flags and the custom XSL. Also ncISO-2.3.5 throws this error but ncISO-2.3.7 completely ignores the flag and uses the default style sheet therefore no errors generated...

**Comment by zdefne-usgs** [comment]
Closing this because it is related to the standalone ncISO (posted here by mistake).  But the error message is generated by the following line in thredssIso I believe...
Any comments @lesserwhirls ?  

https://github.com/Unidata/threddsIso/blob/d19c0637b2fba1e4edd422a686ed8df6fd52a684/nciso-common/src/main/java/thredds/server/metadata/nciso/util/ThreddsTranslatorUtil.java#L261

			String err = "Configuration problem: "+xsltFile+" TransformerConfigurationException. "+

**Comment by lesserwhirls** [comment]
Hello @zdefne-usgs - I think I see what is happening. Two things.

1. The commandline argument is `-xsl`, not `-xslt`
2. The xsl file needs to be live in a directory called `xsl`, and that directory must live in the same directory as the jar file.

I coordination with NOAA-PMEL, I had made an attempt at combining the standalone codebase with the plugin codebase so that there could be a one-stop shot, and did a few updates in terms of dependencies (like using the latest netCDF-Java), etc. The current release of that jar can be found at https://artifacts.unidata.ucar.edu/repository/unidata-releases/EDS/nciso/2.4.3/nciso-2.4.3-commandline.jar if you are interested in giving it a spin.

Cheers,

Sean

**Comment by zdefne-usgs** [comment]
@lesserwhirls if we want make changes the style sheet that generates the iso.XML directly on our thredds server (instead of using a standalone script) how can we do it?  Is it something that can be done post server installation (like replacing the style sheet)?

**Comment by lesserwhirls** [comment]
Do you see anything in the `ncIso.log` file (should be in the same directory as the `nciso-2.4.3-commandline.jar` file)?

**Comment by zdefne-usgs** [comment]
There is some of this...
```
...
INFO  [main] g.n.e.c.ServiceController.[%PARSER_ERROR[x]] Jan/24 22:07:33 - Running service controller...
INFO  [main] g.n.e.c.ServiceController.[%PARSER_ERROR[x]] Jan/24 22:07:33 - Launch start time: 24 Jan 2022 10:07
INFO  [main] g.n.e.t.b.ThreddsDatasetTree.[%PARSER_ERROR[x]] Jan/24 22:07:33 - displayName=ROOT
INFO  [main] g.n.e.s.DatasetTreeService.[%PARSER_ERROR[x]] Jan/24 22:07:33 - rootNode=breach_matanzas
INFO  [main] g.n.e.t.s.i.CatalogCrawlerImpl.[%PARSER_ERROR[x]] Jan/24 22:07:34 - maxDepth: 1 depth: 0 dataset.getFullName():00_dir_roms.ncml; dataset.hasAccess(): true maxLeaves: 20 leafcnt: 0
INFO  [main] g.n.e.t.s.i.CatalogCrawlerImpl.[%PARSER_ERROR[x]] Jan/24 22:07:34 - allowable service
INFO  [main] g.n.e.t.s.i.CatalogCrawlerImpl.[%PARSER_ERROR[x]] Jan/24 22:07:34 - adding mdc
INFO  [main] g.n.e.t.s.i.CatalogCrawlerImpl.[%PARSER_ERROR[x]] Jan/24 22:07:34 - maxDepth: 1 depth: 0 dataset.getFullName():00_dir_roms_ISO.xml; dataset.hasAccess(): true maxLeaves: 20 leafcnt: 1
INFO  [main] g.n.e.t.s.i.CatalogCrawlerImpl.[%PARSER_ERROR[x]] Jan/24 22:07:34 - allowable service
INFO  [main] g.n.e.t.s.i.CatalogCrawlerImpl.[%PARSER_ERROR[x]] Jan/24 22:07:34 - adding mdc
...
```
and some of that...
```
...
INFO  [main] g.n.e.t.b.ThreddsDatasetTree.[%PARSER_ERROR[x]] Jan/24 22:07:35 - found: /geoport.usgs.esipfed.org/thredds/dodsC/vortexfs1/usgs/Projects/breach/breach_matanzas/
INFO  [main] g.n.e.t.b.ThreddsDatasetTree.[%PARSER_ERROR[x]] Jan/24 22:07:35 - displayName=coamps_wind_7318.nc
INFO  [main] t.s.m.n.u.ThreddsExtentUtil.[%PARSER_ERROR[x]] Jan/24 22:07:38 - FeatureType is null or a GRID getting extent from axes: GRID
INFO  [main] t.s.m.n.u.ThreddsExtentUtil.[%PARSER_ERROR[x]] Jan/24 22:07:38 - numTimeElems=722
INFO  [main] t.s.m.n.u.ThreddsExtentUtil.[%PARSER_ERROR[x]] Jan/24 22:07:38 - axisName=ocean_time
INFO  [main] t.s.m.n.u.ThreddsExtentUtil.[%PARSER_ERROR[x]] Jan/24 22:07:38 - Total Memory: 1024
INFO  [main] t.s.m.n.u.ThreddsExtentUtil.[%PARSER_ERROR[x]] Jan/24 22:07:38 - Free Memory: 995
INFO  [main] t.s.m.n.u.ThreddsExtentUtil.[%PARSER_ERROR[x]] Jan/24 22:07:38 - udunits string = 4.9825152E9 seconds since 1858-11-17 00:00:00
ERROR [main] t.s.m.n.u.ThreddsTranslatorUtil.[%PARSER_ERROR[x]] Jan/24 22:07:42 - Could not load NETCDF file: https://geoport.usgs.esipfed.org/thredds/dodsC/vortexfs1/usgs/Projects/breach/breach_matanzas/00_dir_roms_ISO.xml because of Exception. https://geoport.usgs.esipfed.org/thredds/dodsC/vortexfs1/usgs/Projects/breach/breach_matanzas/00_dir_roms_ISO.xml is not a valid URL, return status=400
java.io.IOException: https://geoport.usgs.esipfed.org/thredds/dodsC/vortexfs1/usgs/Projects/breach/breach_matanzas/00_dir_roms_ISO.xml is not a valid URL, return status=400
	at ucar.nc2.dataset.DatasetUrl.checkIfCdmr(DatasetUrl.java:402)
	at ucar.nc2.dataset.DatasetUrl.disambiguateHttp(DatasetUrl.java:388)
	at ucar.nc2.dataset.DatasetUrl.findDatasetUrl(DatasetUrl.java:154)
	at ucar.nc2.dataset.NetcdfDatasets.openDataset(NetcdfDatasets.java:134)
	at ucar.nc2.dataset.NetcdfDatasets.openDataset(NetcdfDatasets.java:118)
	at ucar.nc2.dataset.NetcdfDatasets.openDataset(NetcdfDatasets.java:104)
	at thredds.server.metadata.nciso.util.ThreddsTranslatorUtil.doGetNcml(ThreddsTranslatorUtil.java:86)
	at thredds.server.metadata.nciso.util.ThreddsTranslatorUtil.getNcml(ThreddsTranslatorUtil.java:78)
	at gov.noaa.eds.service.DatasetTreeService.getNodes(DatasetTreeService.java:159)
	at gov.noaa.eds.service.DatasetTreeService.getNodes(DatasetTreeService.java:234)
	at gov.noaa.eds.service.DatasetTreeService.getNodes(DatasetTreeService.java:234)
	at gov.noaa.eds.service.DatasetTreeService.getNodes(DatasetTreeService.java:234)
	at gov.noaa.eds.service.DatasetTreeService.getNodes(DatasetTreeService.java:234)
	at gov.noaa.eds.service.DatasetTreeService.getNodes(DatasetTreeService.java:234)
	at gov.noaa.eds.service.DatasetTreeService.getNodes(DatasetTreeService.java:234)
	at gov.noaa.eds.service.DatasetTreeService.getNodes(DatasetTreeService.java:234)
	at gov.noaa.eds.service.DatasetTreeService.getNodes(DatasetTreeService.java:234)
	at gov.noaa.eds.service.DatasetTreeService.generateTree(DatasetTreeService.java:318)
	at gov.noaa.eds.controller.ServiceController.launch(ServiceController.java:69)
	at gov.noaa.eds.controller.ServiceController.main(ServiceController.java:125)
...
```
Any thoughts? Thanks for looking into it...

**Comment by zdefne-usgs** [comment]
@lesserwhirls to follow up with my previous post with more information. More has been discussed on the ncISO repo
https://github.com/NOAA-PMEL/uafnciso/issues/21

To summarize, the version of Java seems to matter and users may have different experience when they run the command on their system. The error I had above when running nciso-2.4.3-commandline.jar was with the following set up:
```
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (build 16.0.2+7, mixed mode, sharing)
```
When I downgraded to Java8 (which worked with ncISO_v.2.3.7.jar) I got an error message saying that nciso-2.4.3-commandline.jar was compiled with a newer version. 

ncISO has updated to v.2.3.8 to fix this issue and I can run it either with java8 or java16 and get the same behavior. But now I get errors that complain about "as=string" tags in the XSL. It looks like this is an issue with XSLT1.0 but not with XSLT2.0 (see [here](http://xml.apache.org/xalan-j/) for more info).
 
-what version of java was use to compile nciso-2.4.3-commandline.jar? 
-was the XSLT version downgraded from 2.0 to 1.0 sometime in the past?  I see a similar discussion here:
https://github.com/Unidata/threddsIso/issues/19#issuecomment-180541999
-when I replace the UnidataDD2MI.xsl on our Thredds server the customizations are applied correctly. How can I compare the standalone ncISO to what I have on the server (apple to apple comparison)?

**Comment by lesserwhirls** [comment]
I'm guessing JDK 11 was used to compile nciso-2.4.3-commandline.jar since that is what the TDS requires. The xsl file used by nciso and the tds iso plugin have diverged, and that was the only remaining task to complete to finalize merging the code bases (which would allow an apples to apples comparison). Glad to hear the issue is fixed over on the uafnciso repository. I guess there are no longer plans to [merge the two codebases](https://github.com/Unidata/threddsIso/issues/46)? Tagging @ethanrd, as he may have more up-to-date information on where that effort stands.
